apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress   
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /tweet
        pathType: Prefix
        backend:
          service:
            name: tweet-api-service
            port:
              number: 8081
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-api-service
            port:
              number: 8083



