# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example-ingress   
#     annotations:
#     # Use the Kubernetes internal DNS to resolve the service name and port
#     nginx.ingress.kubernetes.io/auth-url: "http://auth-api-service.default.svc.cluster.local:8083/auth/validate"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend-service
#             port:
#               number: 80
#       - path: /tweet
#         pathType: Prefix
#         backend:
#           service:
#             name: tweet-api-service
#             port:
#               number: 8081
#       - path: /user
#         pathType: Prefix
#         backend:
#           service:
#             name: user-api-service
#             port:
#               number: 8082
#       - path: /auth
#         pathType: Prefix
#         backend:
#           service:
#             name: auth-api-service
#             port:
#               number: 8083



# asdas
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress 
  annotations:
    # Use Nginx as the ingress controller
    kubernetes.io/ingress.class: "nginx"
    # Enable CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # Authenticate requests
    nginx.ingress.kubernetes.io/auth-url: "http://auth-api-service.twix.svc.cluster.local:8083/auth/validate"
    # nginx.ingress.kubernetes.io/auth-signin: "http://auth-api-service.twix.svc.cluster.local:8083/auth/generateAccessToken"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      satisfy any;
      auth_request_set $auth_status $upstream_status;
      if ($request_uri ~* "^/user/login|^/user/register") {
        set $auth_status 200;
      }
      if ($auth_status = 401) {
        return 401;
      }
  
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /tweet
        pathType: Prefix
        backend:
          service:
            name: tweet-api-service
            port:
              number: 8081
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      - path: /user/login
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      - path: /user/register
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      # - path: /auth
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: auth-api-service
      #       port:
      #         number: 8083



