apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth-api-service.default.svc.cluster.local/validate"
    nginx.ingress.kubernetes.io/auth-method: "GET"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Skip authentication for specific paths
      set $skip_auth 0;
      if ($request_uri ~* "^/user/login") {
        set $skip_auth 1;
      }
      if ($request_uri ~* "^/user/register") {
        set $skip_auth 1;
      }
      if ($skip_auth = 0) {
        auth_request /validate;
      }
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /user/register
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      - path: /user/login
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user-api-service
            port:
              number: 8082
      - path: /tweet
        pathType: Prefix
        backend:
          service:
            name: tweet-api-service
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80




















# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example-ingress   
#   # namespace: ingress-nginx
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend-service
#             port:
#               number: 80
#       - path: /tweet
#         pathType: Prefix
#         backend:
#           service:
#             name: tweet-api-service
#             port:
#               number: 8081
#       - path: /user
#         pathType: Prefix
#         backend:
#           service:
#             name: user-api-service
#             port:
#               number: 8082


